"""Banque de Reels — @sabine_hypersensible.

Chaque entrée : n (numéro de la vérité, None = « 101 VÉRITÉS »), hook (3 lignes, \n = saut),
texto (paragraphes lus par la voix et affichés un par un), leyenda (légende Instagram).
*mot* = écrit en rouge manuscrit (un dans le hook, un dans le dernier paragraphe).
Source : « 101 vérités que ton hypersensibilité essaie de te dire », Sabine Mercier.
"""

FRASES = [
    # 1
    dict(n=1, hook="« Trop sensible »\nn'a jamais été\nun *diagnostic*.",
         texto=["C'est juste le mot des gens qui ressentent moins que toi.",
                "Pour une bougie, une lampe est trop lumineuse. Ça ne dit rien sur la lampe. Ça dit seulement que les deux ne sont pas réglées pareil.",
                "Là où les autres perçoivent un murmure, tu entends une phrase entière.",
                "Ce n'est pas de l'excès. C'est de la *précision.*"],
         leyenda="Tu n'as pas de défaut de fabrication. Tu as un seuil différent. ✨"),
    # 2
    dict(n=40, hook="Ton angoisse monte\nle soir ? Ce n'est\npeut-être pas de l'*anxiété*.",
         texto=["Toute la journée, tu as tenu, encaissé, avancé, sans prendre le temps de digérer ce qui te traversait.",
                "Le soir, quand le bruit retombe, tout remonte d'un coup.",
                "Ce n'est pas toujours un drame caché. C'est souvent une journée trop pleine qui n'a pas pu redescendre.",
                "Et un corps trop plein ne se vide pas en réfléchissant. Il se vide en *ralentissant.*"],
         leyenda="Le silence du soir laisse enfin remonter ce que le bruit du jour avait recouvert. 🌙"),
    # 3
    dict(n=26, hook="Une belle soirée,\npuis deux jours\npour t'en *remettre* ?",
         texto=["Il y a un mot pour ça : la « gueule de bois sociale ».",
                "Pendant toute la soirée, ton cerveau n'a rien filtré : les conversations à trois tables de là, la musique, l'humeur de chacun.",
                "Le plaisir et le coût sont deux choses séparées. Tu as vraiment aimé la soirée, et elle t'a vraiment coûté cher en énergie.",
                "Tu n'as pas besoin de moins aimer les gens. Tu as besoin de te *reposer* après."],
         leyenda="Une soirée, puis un matin calme. Ça n'enlève rien au plaisir de la veille. ☕"),
    # 4
    dict(n=89, hook="Si un coucher de soleil\npeut te faire pleurer,\nc'est une *bonne* nouvelle.",
         texto=["Le capteur qui te fait souffrir dans une pièce bruyante, c'est le même qui te fait pleurer devant un morceau de musique.",
                "Celui qui absorbe la tristesse des autres, c'est le même qui te fait vibrer devant un ciel que personne autour de toi ne lève les yeux pour voir.",
                "Ta sensibilité n'a pas deux réglages. Elle n'en a qu'un, et il est réglé sur intense.",
                "Tu ne portes pas seulement le poids du monde. Tu en reçois aussi toute la *lumière.*"],
         leyenda="Le même capteur, pour la douleur comme pour la beauté. ☀️"),
    # 5
    dict(n=87, hook="Tu « sens » les gens\navant qu'ils parlent ?\nCe n'est pas *magique*.",
         texto=["Ton cerveau capte une multitude de micro-signaux : un ton, un geste, un détail.",
                "Il en tire une conclusion presque instantanée, avant même que ta conscience ait suivi.",
                "Ce que tu appelles « pressentiment » est une déduction éclair, faite à partir d'informations bien réelles.",
                "Arrête de te dire que tu te fais des idées. Apprends à lui faire *confiance.*"],
         leyenda="Ton intuition ne te dit pas n'importe quoi. Elle a juste calculé plus vite que toi. 🔍"),
    # 6
    dict(n=20, hook="Ce néon qui grésille,\npersonne ne l'entend…\n*sauf toi*.",
         texto=["Le frigo qui ronronne. La conversation à deux tables de là. Pour la plupart des gens, tout ça disparaît en arrière-plan.",
                "Ton cerveau, lui, n'arrive pas à le ranger dans la case « à ignorer ».",
                "Ce n'est pas un caprice. Il n'a simplement pas le bouton qui met les sons parasites en sourdine.",
                "Tu as le droit de protéger tes oreilles, sans *culpabiliser.*"],
         leyenda="Un casque, une pièce calme : ce n'est pas un luxe, c'est un réglage. 🎧"),
    # 7
    dict(n=60, hook="Ton besoin de plaire\nn'est pas une faiblesse.\nC'est un *radar*.",
         texto=["Tu sens quand quelqu'un est déçu de toi, avant même qu'un mot soit dit.",
                "Ce signal te transperce. Alors tu t'adaptes, tu dis oui, tu te plies.",
                "Ce n'est pas que tu tiens à leur avis plus que de raison. Tu ressens leur déception dans ton corps.",
                "L'enjeu : apprendre à sentir ce signal sans t'y *soumettre.*"],
         leyenda="Tu n'as jamais quémandé. Tu captes juste plus fort que les autres. 📶"),
    # 8
    dict(n=None, hook="Tu n'as jamais\nété trop. Tu as\ntoujours été *toi*.",
         texto=["Là où les autres perçoivent un murmure, tu entends une phrase entière.",
                "Là où ils traversent une pièce sans rien remarquer, tu captes les regards, les tensions, les non-dits.",
                "Ni une maladie, ni une mode, ni une faiblesse : un trait, aussi ancien que le vivant.",
                "Tu ne l'as pas choisi. Mais tu peux, enfin, apprendre à le *comprendre.*"],
         leyenda="Une personne sur cinq environ est faite comme toi. 🌞"),
    # 9
    dict(n=94, hook="Tu pleures\n« pour un rien » ?\nC'est une *soupape*.",
         texto=["Quand ton système a accumulé, encaissé, retenu toute la journée, les larmes font le ménage.",
                "Elles évacuent une tension qui, sinon, se déposerait ailleurs : dans ta nuque, ton ventre, ton sommeil.",
                "Ce n'est pas un signe que tu vas mal.",
                "C'est souvent ce qui te permet d'aller *mieux.*"],
         leyenda="Laisse couler quand ça vient. Ce ne sont pas des larmes de faiblesse. 💧"),
    # 10
    dict(n=35, hook="Un rien t'agace\nen fin de journée ?\nTon réservoir est *plein*.",
         texto=["Après trop de bruit et de monde, ton système n'a plus de marge, plus de patience, plus d'énergie pour amortir quoi que ce soit.",
                "Le moindre stimulus en plus déborde en agacement.",
                "Ce n'est pas ton fond. C'est le voyant rouge d'un réservoir au maximum.",
                "Repère-le plus tôt, et accorde-toi une *pause.*"],
         leyenda="Tu n'es pas quelqu'un de désagréable. Tu es quelqu'un de saturé. 🔋"),
    # 11
    dict(n=None, hook="Quelle vérité\nt'a fait dire :\n« c'est *moi* » ?",
         texto=["Le bruit de fond que personne ne remarque ?",
                "La gueule de bois sociale après une soirée réussie ?",
                "L'angoisse qui monte le soir, alors que tout va bien ?",
                "Dis-moi laquelle en commentaire. Il y en a une écrite pour *toi.*"],
         leyenda="Quelque part dans ces 101 vérités, il y en a une écrite pour toi. 💬"),
    # 12
    dict(n=83, hook="Ton besoin\nde solitude n'est\npas un *repli*.",
         texto=["Après avoir capté, absorbé, ressenti toute la journée, tu as besoin d'un espace sans stimulation pour te reconstituer.",
                "C'est ton atelier : là que tu ranges ce qui s'est accumulé et que tu retrouves tes forces.",
                "L'isolement coupe du monde. Ta solitude, elle, te répare et te rend *disponible.*"],
         leyenda="Ce n'est pas une fuite du monde. C'est l'endroit où tu te recharges. 🌿"),
    # 13
    dict(n=82, hook="Tu souffres plus\nque les autres ?\nTu *fleuris* plus aussi.",
         texto=["Le même système qui déborde dans le chaos s'épanouit, plus que la moyenne, dès que le cadre est bon.",
                "La réceptivité qui t'expose au pire t'ouvre aussi au meilleur.",
                "Mauvais terrain, tu fanes. Bon terrain, tu fleuris comme peu de gens savent fleurir.",
                "Choisis mieux tes *terrains.*"],
         leyenda="Tes lieux, tes gens, tes rythmes : pour toi, l'environnement n'est pas un détail. 🌸"),
    # 14
    dict(n=85, hook="Tu as le droit\nde partir\n*plus tôt*.",
         texto=["De baisser le son. De dire simplement : « c'est trop pour moi ».",
                "Ces besoins ne sont pas des caprices. Ce sont ceux d'un système qui a atteint sa limite.",
                "La première fois que j'ai osé, j'étais persuadée de gâcher la soirée de tout le monde. Personne n'a rien remarqué.",
                "Chaque fois que tu dis stop, tu poses un acte de *respect* envers toi-même."],
         leyenda="Ton confort ne compte pas moins que le leur. 🤍"),
    # 15
    dict(n=39, hook="Et si ton anxiété\nétait ton corps\nqui dit *stop* ?",
         texto=["Le cœur qui s'emballe, cette boule, cette impression floue que quelque chose ne va pas.",
                "Tu fouilles ta journée pour trouver le problème, et ton esprit t'invente des scénarios.",
                "Mais il n'y a peut-être aucun drame caché. Juste un système nerveux qui a reçu trop, sans jamais avoir le temps de redescendre.",
                "Tu cherches dans ta tête une réponse qui est dans ton *corps.*"],
         leyenda="Ton corps ne sait pas dire « je suis saturé » avec des mots. Alors il le dit autrement. 🫀"),
    # 16
    dict(n=22, hook="Pourquoi une foule\nt'épuise autant ?\nVoici la *raison*.",
         texto=["Dans une foule, tu ne perçois pas un décor flou. Tu captes les visages, les tensions, les éclats de voix.",
                "Là où les autres voient « du monde », tu reçois cent signaux distincts en même temps.",
                "Ton cerveau essaie de tout traiter, et ça consomme une énergie folle.",
                "Tu as le droit de t'y préparer, ou d'en sortir *tôt.*"],
         leyenda="La foule, pour toi, ce n'est jamais une seule chose. C'est cent choses à la fois. 🚉"),
    # 17
    dict(n=5, hook="On te dit que tu\nte fais des idées ?\nTu vois en *HD*.",
         texto=["Un ami ne va pas bien, et tu l'as senti avant qu'il ouvre la bouche.",
                "Tu captes des signaux réels : un micro-changement de voix, un regard qui fuit, une épaule un peu trop haute.",
                "Un écran basse définition affiche l'image. Un écran haute définition montre le grain et les nuances.",
                "Ton radar n'est pas déréglé. Il est plus *fin* que la moyenne."],
         leyenda="Ce qu'on appelle « trop analyser », c'est percevoir ce que les autres ne perçoivent pas. 🔎"),
    # 18
    dict(n=26, hook="Je m'en voulais\ndu contrecoup.\nMaintenant, je le *planifie*.",
         texto=["Après chaque soirée un peu dense, je me réveillais lessivée, et je m'en voulais.",
                "Comme si ce contrecoup prouvait que quelque chose clochait chez moi.",
                "Aujourd'hui, je prévois : une soirée, puis un matin calme.",
                "Ça n'enlève rien au *plaisir* de la veille."],
         leyenda="Le lendemain, ton système paie l'addition. Autant le prévoir. 🗓️"),
    # 19
    dict(n=61, hook="Dire non\nte fait mal ?\nC'est *réel*.",
         texto=["Pour beaucoup, refuser est un petit inconfort. Pour toi, c'est une boule, une culpabilité qui ronge des heures.",
                "Anticiper la déception de l'autre active en toi les mêmes circuits que la douleur physique.",
                "Alors chaque fois que tu y arrives, ce n'est pas de la dureté. C'est du courage.",
                "Ce non fait bien moins de dégâts que tous ces oui qui t'*épuisent.*"],
         leyenda="Le non ne sera jamais indolore. Mais tu peux le dire quand même. ✋"),
    # 20
    dict(n=93, hook="Solide\nne veut pas dire\n*dur*.",
         texto=["On t'a fait croire que pour être solide, il fallait se blinder.",
                "La dureté ferme tout et se coupe de ce qu'elle ressent. La solidité ressent pleinement, et tient debout quand même.",
                "Un arbre solide n'est pas un poteau rigide. Il plie, il bouge avec le vent, et tient par ses racines.",
                "Tu peux être cet *arbre.*"],
         leyenda="Les plus solides sont souvent ceux qui ressentent le plus. 🌳"),
    # 21
    dict(n=52, hook="Tout va bien\net tu angoisses\nquand *même* ?",
         texto=["Rien de grave, rien à signaler, et pourtant l'angoisse est là. Alors tu te juges sévèrement.",
                "Mais rien ne va mal chez toi. Ton système est resté en alerte alors que le danger est passé depuis longtemps.",
                "Ton angoisse ne parle pas de ta vie présente. Elle parle de l'état de ton système nerveux.",
                "Il a juste besoin qu'on l'aide à *couper.*"],
         leyenda="Ça se travaille, doucement, sans te juger d'y être encore. 🕊️"),
    # 22
    dict(n=24, hook="Ta fatigue\nn'est pas de\nla *paresse*.",
         texto=["Pense à tout ce que ton cerveau traite en continu : chaque bruit, chaque lumière, chaque émotion autour de toi.",
                "Pendant que d'autres avancent l'esprit léger, le tien tourne à plein régime, du matin au soir.",
                "Ta fatigue est la facture d'un système qui travaille beaucoup plus que la moyenne, sans que ça se voie.",
                "Tu as le droit de te reposer autant qu'elle l'*exige.*"],
         leyenda="Une dépense invisible reste une vraie dépense. 🔋"),
    # 23
    dict(n=None, hook="Ce qu'on te reproche\net ce que c'est\n*vraiment*.",
         texto=["Ta lenteur à décider ? Un cerveau qui explore toutes les branches.",
                "Ton besoin de solitude ? Ton atelier de recharge.",
                "Ton irritabilité du soir ? Un réservoir à ras bord.",
                "Ta « susceptibilité » ? De la porosité, le revers de ta *sensibilité.*"],
         leyenda="On a souvent mal traduit ce que tu vis. 🔄"),
    # 24
    dict(n=11, hook="Au bord des larmes\ndans un supermarché\ntrop *éclairé* ?",
         texto=["Ces jours-là, entendre que ta sensibilité est un superpouvoir sonne creux. Tu le sais.",
                "Ce n'est pas magique. Certains jours sont lourds, épuisants, franchement injustes.",
                "D'autres sont pleins de grâce. Comme toute chose humaine.",
                "Tu n'as pas besoin d'un conte de fées. Tu as besoin qu'on regarde ta réalité *en face.*"],
         leyenda="C'est dans cette honnêteté que la réconciliation devient possible. 🌗"),
    # 25
    dict(n=57, hook="Tu sens l'ambiance\nd'une pièce avant\nqu'on *parle* ?",
         texto=["Tu entres quelque part, et en quelques secondes tu sais. Quelqu'un a pleuré. Le couple près de la fenêtre s'est disputé.",
                "Tu lis sans t'en rendre compte une foule de signaux : les postures, les regards qui s'évitent, un silence trop lourd.",
                "Tu prends la température d'une pièce comme d'autres avec un thermomètre.",
                "C'est aussi pour ça qu'on se sent *compris* avec toi."],
         leyenda="Tu n'inventes pas ces ambiances. Tu les perçois, avant les mots. 🌡️"),
    # 26
    dict(n=86, hook="La nature te calme\nplus que tout ?\nC'est *physiologique*.",
         texto=["Quelques minutes au milieu des arbres, au bord de l'eau, et quelque chose se dénoue.",
                "Pas de néons, pas de brouhaha, pas de sollicitations. Juste des régularités douces : les feuilles, l'eau, un rythme lent.",
                "Pour un système saturé par l'artificiel, c'est un vrai bain de calme.",
                "Une marche dans les arbres n'est pas un luxe. C'est un *soin.*"],
         leyenda="Prends la nature au sérieux, comme un vrai outil. 🌳"),
    # 27
    dict(n=48, hook="Tes pensées\ntournent la nuit ?\nTon cerveau *range*.",
         texto=["La conversation de l'après-midi, la phrase que tu aurais dû dire, un souvenir vieux de dix ans.",
                "Toute la journée, ton cerveau a capté sans avoir le temps de traiter. Le soir, il s'y met enfin, en désordre.",
                "Ce n'est pas un défaut. C'est un cerveau débordé qui essaie de classer.",
                "Offre-lui un moment pour déposer dans la journée, et tes nuits *s'allègent.*"],
         leyenda="Ton cerveau ne rumine pas pour te torturer. Il cherche où poser. 🌙"),
    # 28
    dict(n=31, hook="Envie soudaine\nde quitter la pièce ?\nC'est une *sécurité*.",
         texto=["En plein repas de famille, ça monte : l'envie de sortir, de trouver une pièce vide.",
                "Ce n'est pas un caprice. Ton système a atteint son seuil et réclame de baisser le flux.",
                "Je m'éclipsais dix minutes dans une chambre, assise dans le noir, juste pour tenir jusqu'au bout de la soirée.",
                "C'est exactement ce qui me permettait de *rester.*"],
         leyenda="Un pas dehors, quelques minutes au calme : ce n'est pas de l'impolitesse. 🚪"),
    # 29
    dict(n=71, hook="Une critique\nte transperce ?\nC'est de la *porosité*.",
         texto=["Là où un autre hausserait les épaules, tu y repenses des heures, des jours.",
                "Les mots ne glissent pas sur toi. Ils entrent, ils résonnent longtemps à l'intérieur.",
                "Le même système qui t'ouvre à la beauté et aux autres te rend perméable aux mots durs. C'est la même ouverture.",
                "Ce n'est pas de la susceptibilité. N'ajoute pas la honte à la *douleur.*"],
         leyenda="Un reproche te traverse vraiment. C'est déjà assez lourd. 🍂"),
    # 30
    dict(n=17, hook="On te dit\nque tu en fais\n*trop* ?",
         texto=["Tu prépares tout dans le détail. Tu penses à ce que les autres oublient. Tu ressens plus fort, tu anticipes plus loin.",
                "Trop par rapport à quoi ? À une norme qui n'est pas la tienne.",
                "Te demander d'en faire moins, c'est comme demander à une personne de grande taille de se baisser en permanence.",
                "Tu ne fais pas trop. Tu fais à ta *mesure.*"],
         leyenda="Ton « trop » est simplement ton juste. 📏"),
    # 31
    dict(n=47, hook="3 gestes qui calment\nton système mieux\nqu'une *pensée*.",
         texto=["Une expiration plus longue que l'inspiration.",
                "Un poids sur toi : une couverture lourde, une main pressée sur le ventre.",
                "Le froid de l'eau sur le visage, ou la lenteur d'une marche.",
                "Ces gestes parlent à ton système nerveux sans passer par les mots. Ils lui disent : tu peux *redescendre.*"],
         leyenda="Quand l'angoisse monte, range l'analyse et va vers le corps. 🌬️"),
    # 32
    dict(n=28, hook="Tu ne ressens rien\nen pleine crise ?\nTon cœur se *protège*.",
         texto=["Une annonce difficile, un choc, et c'est le vide. Après coup, tu te demandes si tu as un cœur.",
                "Tu en as un, immense. C'est justement pour ça que ça arrive.",
                "Quand l'émotion risque d'être trop forte, ton système coupe le courant, comme un fusible qui saute.",
                "L'émotion revient plus tard, quand tu es en *sécurité.*"],
         leyenda="Ce n'était pas un manque de cœur. C'était ton cœur qui se mettait à l'abri. 🛡️"),
    # 33
    dict(n=62, hook="Tu excuses toujours\nceux qui te blessent ?\nVoici *pourquoi*.",
         texto=["« Il a dû souffrir pour en arriver là. » « Ce n'est pas vraiment sa faute. »",
                "Quand quelqu'un te fait du mal, tu ressens aussi ce qui se passe en lui : sa blessure, son manque.",
                "Ta douleur passe au second plan, parce que la sienne, tu la ressens de l'intérieur.",
                "Tu peux comprendre quelqu'un et te mettre à l'*abri.*"],
         leyenda="Une main qui comprend, une main qui protège. 🤲"),
    # 34
    dict(n=100, hook="Le monde a besoin\nde gens qui\nressentent *fort*.",
         texto=["Ceux qui remarquent la personne qui va mal avant les autres. Ceux qui perçoivent l'injustice discrète, la fausse note.",
                "Ceux qui refusent la superficialité et créent des œuvres qui touchent.",
                "Sans eux, le monde irait plus vite, plus fort, plus dur. Et plus aveugle.",
                "Tu fais partie de ceux-là. Ce n'est pas rien. C'est même ce qui *manque.*"],
         leyenda="Là où d'autres passent sans voir, toi tu remarques. 🌍"),
    # 35
    dict(n=41, hook="Tu cherches pourquoi\ntu angoisses ?\nTon mental *invente*.",
         texto=["Ton esprit déteste ne pas comprendre. « C'est peut-être ce mail. » « Et si ça tournait mal ? »",
                "Souvent, la sensation vient d'abord. L'explication vient après.",
                "Ton mental fabrique une histoire pour donner du sens à ce que ton corps ressent.",
                "Change la question : pas « pourquoi j'angoisse ? », mais « mon corps est-il simplement *plein* ? »"],
         leyenda="Souvent, la réponse est là. Et elle demande juste de te déposer. 🧺"),
    # 36
    dict(n=21, hook="Une étiquette\nqui gratte peut\nruiner ta *journée* ?",
         texto=["Une couture de chaussette mal placée. Une lumière un peu trop vive.",
                "Pour ton système nerveux, ce n'est pas « si peu ». Ton cerveau traite ces détails avec le même sérieux qu'un signal important.",
                "Comme une petite alarme qu'on n'arrive pas à éteindre.",
                "Un inconfort que tu ne peux pas ignorer mérite qu'on le *retire.*"],
         leyenda="Pas qu'on s'en moque. Qu'on le retire. ✂️"),
    # 37
    dict(n=7, hook="Adorer les gens\net avoir besoin\ndu *noir* ensuite.",
         texto=["Tu peux passer une soirée merveilleuse, rire à en avoir mal, et savoir que tu auras besoin de t'isoler après.",
                "Ce n'est pas que tu n'aimes pas le monde. Ton système reçoit tout à plein volume.",
                "Il lui faut ensuite un endroit calme pour tout ranger.",
                "Le besoin de solitude qui suit n'annule pas le plaisir d'*avant.*"],
         leyenda="Tu vis tout intensément, y compris le repos. 🌙"),
    # 38
    dict(n=20, hook="Un open space entier,\net un seul néon\nqui me *vrillait* la tête.",
         texto=["Longtemps, j'ai cru que je devenais folle de ne pas supporter ce que personne d'autre ne semblait entendre.",
                "J'ai mis des années à comprendre que je n'étais pas difficile.",
                "Mon cerveau n'avait simplement pas le bouton qui met les sons parasites en sourdine.",
                "Le tien non plus, peut-être. Et ce n'est pas un *caprice.*"],
         leyenda="Un casque, une pièce calme : j'ai fini par me les autoriser. 🎧"),
    # 39
    dict(n=77, hook="Aimer fort\nsans te perdre\ndans l'*autre*.",
         texto=["Quand tu aimes, tu as tendance à te fondre : ses humeurs deviennent les tiennes, ses besoins passent avant les tiens.",
                "Se relier, c'est rester deux, proches, en gardant chacun ses contours.",
                "Un lien où l'un disparaît n'est pas plus riche. Il finit par épuiser.",
                "Tu peux garder ton intensité d'amour et tes *contours.*"],
         leyenda="Deux personnes entières qui se choisissent : c'est ça qui dure. 💑"),
    # 40
    dict(n=90, hook="Tu ne peux pas\ngarder que les\nbons *côtés*.",
         texto=["Tu aimerais garder l'émerveillement, la profondeur, l'intensité des joies, et jeter la surcharge et l'épuisement.",
                "Mais tout ça vient du même système. La même ouverture te submerge dans une foule et te bouleverse devant la beauté.",
                "En essayant d'éteindre ta douleur, tu éteins aussi ta joie.",
                "L'accepter, c'est cesser la guerre. Et c'est le début de la *paix.*"],
         leyenda="« Je prends les deux, parce qu'ils sont une seule et même chose. » ☯️"),
    # 41
    dict(n=53, hook="Ton anxiété\nest une jauge,\npas une *ennemie*.",
         texto=["Comme un voyant sur un tableau de bord, elle ne cause pas le problème. Elle le signale.",
                "Quand elle s'allume, elle te dit : tu as dépassé ta limite, il faut ralentir.",
                "Éteindre une jauge ne vide pas le réservoir.",
                "L'écouter, c'est agir avant la *panne.*"],
         leyenda="Elle n'est pas là pour te punir, mais pour t'avertir. ⛽"),
    # 42
    dict(n=34, hook="Le silence n'est pas\nun luxe pour toi.\nC'est un *besoin*.",
         texto=["Ton cerveau traite bien plus d'informations que la moyenne. Il a besoin de plages sans stimulation pour se vider et se réparer.",
                "Sans moments de calme, la surcharge s'installe.",
                "Longtemps, j'ai traité mon besoin de silence comme une faiblesse un peu honteuse.",
                "Une pièce calme en fin de journée n'est pas un plaisir. C'est une *réparation.*"],
         leyenda="Tu as le droit de réclamer ce calme, de le programmer, de le défendre. 🤫"),
    # 43
    dict(n=15, hook="Des heures pour\nchoisir un plat ?\nTon cerveau *explore*.",
         texto=["Pour chaque choix, tu ne vois pas deux options. Tu vois leurs conséquences, dans une semaine, dans un an.",
                "Ton esprit déploie un arbre entier là où d'autres voient une simple bifurcation.",
                "Ce n'est pas un manque. C'est un excès de vision.",
                "Tu peux choisir plus vite, en décidant de te faire *confiance.*"],
         leyenda="Pas de l'indécision : trop de choses à peser. 🌳"),
    # 44
    dict(n=None, hook="4 phrases\nà te dire\n*autrement*.",
         texto=["« Je suis à cran » devient « mon réservoir est plein ».",
                "« Je suis quelqu'un d'anxieux » devient « l'anxiété arrive quand on force ma sensibilité ».",
                "« Pourquoi j'angoisse ? » devient « mon corps est-il simplement plein ? »",
                "« J'en fais trop » devient « je fais à ma *mesure* »."],
         leyenda="Les mots qu'on se dit changent la manière dont on se traite. 📝"),
    # 45
    dict(n=65, hook="Tu portes les émotions\nde tout le monde ?\nEt *toi* ?",
         texto=["Apaiser, réparer, consoler. Tu te sens responsable de l'humeur de chacun.",
                "Il y a de la générosité là-dedans. Mais aussi, parfois, une façon de ne pas regarder ce qui se passe en toi.",
                "Pendant que tu t'occupes de tout le monde, qui s'occupe de ce que tu ressens ?",
                "Tu as le droit, aussi, de revenir vers *toi.*"],
         leyenda="Prendre soin des autres est beau. Pas au point de t'oublier. 💛"),
    # 46
    dict(n=98, hook="Ta « faiblesse »\nest la source de\nta plus belle *richesse*.",
         texto=["Cette réceptivité qui te fatigue te fait ressentir la beauté à en pleurer.",
                "Cette empathie qui t'épuise rend tes liens si profonds.",
                "Cette profondeur qui te complique la vie donne du sens à tout ce que tu touches.",
                "Ce que tu croyais devoir cacher devient ce que tu peux *offrir.*"],
         leyenda="On ne se débarrasse pas de ce qui nous rend vivant. 💗"),
    # 47
    dict(n=49, hook="Une angoisse\n« sans raison » ?\nRegarde *autour* de toi.",
         texto=["Ces mal-êtres diffus qui tombent dessus sans événement précis.",
                "Souvent, ils ont des causes très concrètes : le brouhaha depuis des heures, la foule traversée, le rythme trop rapide.",
                "Ton système les a enregistrées, même si ta conscience ne les a pas pointées du doigt.",
                "Fais l'inventaire : combien de bruit, de monde, de *vitesse* depuis ce matin ?"],
         leyenda="La cause est souvent dehors, pas dans un défaut mystérieux. 🧭"),
    # 48
    dict(n=29, hook="Une scène violente\nà l'écran te fait\n*mal* pour de vrai ?",
         texto=["On te dit de prendre du recul, que ce n'est qu'une image.",
                "Mais quand tu vois quelqu'un souffrir, même à l'écran, ton corps en ressent une partie, physiquement.",
                "La frontière entre ce que tu vois et ce que tu ressens est plus fine chez toi.",
                "Éviter ce qui te blesse inutilement, ce n'est pas fuir. C'est prendre *soin* de toi."],
         leyenda="Tu as le droit de protéger tes yeux de certaines images. 📺"),
    # 49
    dict(n=6, hook="Hypersensible\nne veut pas dire\n*timide*.",
         texto=["La timidité, c'est une peur : celle du regard des autres. Ta sensibilité, elle, est une manière de percevoir.",
                "On peut adorer prendre la parole, monter sur scène, mener une réunion, et avoir besoin de calme après.",
                "Près d'un tiers des personnes réglées comme toi sont extraverties.",
                "Tu as le droit d'être sensible sans être *timide.*"],
         leyenda="Deux choses différentes, qu'on confond trop souvent. 🎤"),
    # 50
    dict(n=64, hook="Ton cœur ouvert\nn'oblige pas\nta porte *ouverte*.",
         texto=["On te présente un faux choix : soit la compassion, soit la protection.",
                "Ce choix n'existe pas. Tu as deux mains. L'une reste tendue vers l'autre. L'autre se lève pour poser une limite.",
                "« Je comprends ce que tu traverses, et je ne te laisserai pas me faire ça. »",
                "C'est la forme la plus mûre de l'*empathie.*"],
         leyenda="Les gens les plus solides tendent une main en levant l'autre. 🤚"),
    # 51
    dict(n=101, hook="Ta sensibilité s'apaise\nle jour où tu cesses\nde la *combattre*.",
         texto=["Pendant longtemps, tu as voulu ressentir moins, t'endurcir, rentrer dans le rang.",
                "Mais on ne gagne pas une guerre contre soi-même. Chaque coup porté à ta sensibilité était un coup porté à toi.",
                "L'apaisement vient le jour où tu poses les armes, et où tu commences à l'habiter.",
                "Tu n'as jamais été trop. Tu ressens le monde en *grand.*"],
         leyenda="Ce n'est pas une résignation. C'est une réconciliation. 🕊️"),
    # 52
    dict(n=42, hook="Réfléchir pour\nte calmer ?\nÇa l'*alimente*.",
         texto=["Quand l'angoisse monte, ton premier réflexe est d'analyser jusqu'à ce que ça se dénoue.",
                "Mais ton cerveau, quand il tourne, ouvre une branche, puis une autre. Pour chaque « et si », il en trouve un nouveau.",
                "C'est comme vouloir éteindre un feu en soufflant dessus.",
                "La sortie est dans ce qui interrompt la pensée : le souffle, le mouvement, le *concret.*"],
         leyenda="Ton mental ne peut pas se calmer lui-même. Va chercher le calme ailleurs. 🌬️"),
    # 53
    dict(n=33, hook="Gorge serrée,\nventre noué ?\nTon corps te *parle*.",
         texto=["Avant même que tu aies compris que quelque chose n'allait pas, ton corps l'a déjà signalé.",
                "Il perçoit la tension d'une situation, l'inconfort d'un lien, la fatigue qui s'accumule.",
                "Ce ne sont pas des symptômes à faire taire. Ce sont des messages envoyés en avance.",
                "Ton corps est ton informateur le plus *rapide.*"],
         leyenda="Il sait avant les mots. 🫶"),
    # 54
    dict(n=3, hook="« Arrête d'y penser »\nn'a jamais marché.\nVoici *pourquoi*.",
         texto=["Ta sensibilité n'est pas une décision que tu prends chaque matin. C'est un câblage, présent bien avant que tu aies des mots pour le dire.",
                "On ne débranche pas un câblage par la volonté.",
                "Tu peux apprendre à l'accompagner, à baisser certaines lumières autour de toi.",
                "Et ce que tu ne peux pas éteindre, tu ne peux pas non plus le *perdre.*"],
         leyenda="Cette manière de ressentir le monde est à toi, pour toujours. 💫"),
    # 55
    dict(n=83, hook="Je rêvais de rentrer\nalors que la soirée\nbattait son *plein*.",
         texto=["Pendant des années, j'ai confondu ce besoin avec un défaut de sociabilité.",
                "Je m'en voulais de vouloir partir alors que les autres s'amusaient.",
                "Puis j'ai compris : ma solitude ne me coupait pas des autres.",
                "C'est elle qui me rendait capable de revenir vers eux *entière.*"],
         leyenda="Ta solitude n'est pas de l'isolement. Elle te répare. 🌿"),
    # 56
    dict(n=70, hook="Tu déclines\nles invitations ?\nTu fais un *tri*.",
         texto=["Tu fuis les grands groupes et les soirées où l'on parle pour ne rien dire. On te colle l'étiquette de « sauvage ».",
                "Mais les liens superficiels te coûtent plus d'énergie qu'ils ne t'en rendent.",
                "Un lien profond plutôt que dix liens vides. Une vraie conversation plutôt qu'une soirée de bavardage.",
                "Refuser le superficiel, c'est faire de la place pour l'*essentiel.*"],
         leyenda="Tu n'as pas besoin de beaucoup de monde. Tu as besoin des bonnes personnes. 🫂"),
    # 57
    dict(n=99, hook="Tu n'as pas\ntrop de sensibilité.\nPas assez d'*espace*.",
         texto=["Toute ta vie, on t'a dit : trop d'émotions, trop de réactions. Et tu as cherché à te réduire.",
                "Renverse la phrase. Peut-être as-tu surtout eu trop peu de lieux calmes, de gens qui comprennent, de temps pour récupérer.",
                "Le problème n'est plus en toi, à corriger. Il est autour de toi, à agrandir.",
                "Des lieux, des liens, des rythmes à ta mesure : tu peux les *construire.*"],
         leyenda="Ce que tu prenais pour un « trop » était exactement ce qu'il fallait. 🌅"),
    # 58
    dict(n=44, hook="Ta sensibilité\net ton anxiété ne sont\npas la même *chose*.",
         texto=["Ta sensibilité, c'est ta nature. Stable, neutre : une manière de percevoir en profondeur.",
                "Ton anxiété apparaît quand cette sensibilité déborde, quand le système reçoit trop, trop longtemps.",
                "La première est permanente. La seconde, non.",
                "Tu n'as pas à guérir de qui tu es. Tu as à l'empêcher de *déborder.*"],
         leyenda="Et ça, c'est possible. 🌤️"),
    # 59
    dict(n=30, hook="Ta nuque toujours\ndure ? Ton corps\ngarde le *score*.",
         texto=["Ce ventre qui se noue. Ces épaules remontées jusqu'aux oreilles.",
                "Tout ce que tu encaisses dans la journée, émotions, tensions captées, surcharge, ne disparaît pas comme par magie.",
                "Quand tu ne l'évacues pas, ça se dépose quelque part. Et ce quelque part, c'est ton corps.",
                "Il réclame que tu l'*écoutes* plus tôt."],
         leyenda="Ce ne sont pas des maux imaginaires. C'est du trop-plein qui a pris forme. 💆"),
    # 60
    dict(n=13, hook="Enfant, tu captais\ndéjà tout ?\nC'était *toi*.",
         texto=["L'enfant qui pleurait devant un dessin animé triste. Qui sentait quand ses parents se disputaient à voix basse.",
                "Qui trouvait les étiquettes insupportables et les fêtes d'anniversaire trop bruyantes.",
                "Ce n'était pas un caprice. C'était déjà ton réglage, présent dès le premier jour.",
                "Et ce petit enfant n'avait rien qui n'allait *pas.*"],
         leyenda="Ce n'est pas venu avec l'âge. C'est ta nature de départ. 🧸"),
    # 61
    dict(n=None, hook="3 phrases\nque tu as le droit\nde *dire*.",
         texto=["« C'est trop pour moi. »",
                "« Je comprends ce que tu traverses, et je ne te laisserai pas me faire ça. »",
                "« Je sais que ça te paraît étrange, et j'en ai besoin quand même. »",
                "Chacune est un acte de *respect* envers toi-même."],
         leyenda="Laquelle as-tu le plus de mal à dire ? 💬"),
    # 62
    dict(n=66, hook="Poser une limite\nn'est pas de\nl'*égoïsme*.",
         texto=["« Non, pas ce soir. » « Je ne peux pas. » Et la culpabilité arrive.",
                "Mais tu reçois, absorbes, portes bien plus que la moyenne. Sans limites, tu te vides jusqu'à la panne.",
                "Tes limites sont les berges qui empêchent la rivière de tout inonder.",
                "Elles te gardent assez de toi pour ne pas *disparaître.*"],
         leyenda="Une limite, ce n'est pas contre les autres. C'est ce qui te permet de tenir. 🌊"),
    # 63
    dict(n=88, hook="Ta sensibilité\nrend ton travail\nplus *vrai*.",
         texto=["À force d'entendre parler de ses difficultés, tu oublies ce qu'elle te donne.",
                "Tes liens sont plus profonds, parce que tu perçois les gens au-delà des apparences.",
                "Ton travail est plus juste, parce que tu remarques ce que les autres survolent. Et si tu crées, les gens ressentent ta nuance.",
                "Tu ne portes pas seulement le poids de ta profondeur. Tu en récoltes les *fruits.*"],
         leyenda="Dans un monde qui reste en surface, aller au fond est précieux. 🎨"),
    # 64
    dict(n=43, hook="Relativiser ?\nTon corps ne\ncomprend pas les *mots*.",
         texto=["« Raisonne-toi. » « Vois les choses autrement. » Des conseils mentaux pour un problème que le mental ne peut pas résoudre.",
                "Le trop-plein n'est pas une erreur de raisonnement. C'est une charge physique à évacuer.",
                "Ralentir le souffle. Sortir marcher. Te mettre au calme, au chaud.",
                "Ton corps ne comprend pas les arguments. Il comprend le *ralentissement.*"],
         leyenda="Ces signaux concrets disent à ton système : le danger est passé. 🍃"),
    # 65
    dict(n=32, hook="Tu ne surréagis pas.\nTu redescends\nplus *lentement*.",
         texto=["Après une dispute, les autres passent à autre chose en quelques minutes. Chez toi, le cœur reste agité, l'esprit rejoue la scène.",
                "Tu n'as pas réagi plus fort. Ton système met juste plus de temps à revenir au calme.",
                "Comme un moteur qui continue de chauffer après qu'on a coupé le contact.",
                "Donne-lui le temps qu'il lui faut. Le calme *reviendra.*"],
         leyenda="Une donnée physiologique, pas un défaut de caractère. ⏳"),
    # 66
    dict(n=9, hook="Une mode récente ?\nOn l'observe chez plus\nde 100 *espèces*.",
         texto=["Ce câblage a été observé chez plus d'une centaine d'espèces animales, des poissons aux primates.",
                "Dans chaque groupe, une partie des individus est réglée pour capter plus et observer avant d'agir.",
                "Si c'était un défaut, la nature ne l'aurait pas gardé partout. Ceux qui sentent le danger en premier protègent tout le monde.",
                "Tu es de cette lignée-là. Elle est vieille comme le *monde.*"],
         leyenda="Le vivant a toujours eu besoin de veilleurs. 🦋"),
    # 67
    dict(n=58, hook="Ton empathie\nn'est pas un choix.\nC'est un *câblage*.",
         texto=["Quelqu'un souffre devant toi, et sa douleur devient un peu la tienne, sans que tu l'aies décidé.",
                "Ton câblage résonne comme une corde qui vibre quand on en pince une autre à côté.",
                "Tu ne peux pas l'éteindre. Mais tu peux apprendre à ressentir sans te noyer.",
                "Le secret : savoir où tu finis et où l'autre *commence.*"],
         leyenda="Ce n'est pas ton empathie qui te fait du mal. 🎻"),
    # 68
    dict(n=96, hook="Et si ton anxiété\nétait une\n*boussole* ?",
         texto=["Quand elle s'allume, elle te dit quelque chose de précis : tu forces ton système contre sa nature.",
                "Trop vite, trop de monde, un rythme qui n'est pas le tien, une limite ignorée une fois de trop.",
                "Au lieu de la combattre, interroge-la : « qu'est-ce que je force en ce moment ? »",
                "Ce que tu vivais comme ton pire ennemi peut devenir ton *guide.*"],
         leyenda="Elle est là pour te ramener à toi. 🧭"),
    # 69
    dict(n=55, hook="Pas besoin d'être\nmoins sensible. Juste\nd'écouter plus *tôt*.",
         texto=["L'erreur, c'est de croire que pour moins angoisser, il faudrait ressentir moins.",
                "Ton anxiété ne vient pas de ta sensibilité. Elle vient du fait que tu l'écoutes trop tard, quand le voyant est déjà rouge.",
                "Il clignotait en orange depuis longtemps.",
                "Pas ressentir moins : ressentir à *temps.*"],
         leyenda="Tu n'as rien à amputer en toi. 🟠"),
    # 70
    dict(n=23, hook="Un café de trop\net ta nuit est\n*gâchée* ?",
         texto=["Le cœur qui s'emballe, l'esprit qui s'agite. On te dit que « ce n'est qu'un café ».",
                "Mais un système nerveux plus réactif répond plus fort à tout ce qui l'excite, y compris ce que tu avales.",
                "Ce n'est pas de la fragilité. C'est de la cohérence.",
                "Une fois que tu le sais, tu trouves ton propre *dosage.*"],
         leyenda="Le bon dosage, c'est celui de ton système, pas celui des autres. ☕"),
    # 71
    dict(n=21, hook="J'ai passé une soirée\nentière à cause\nd'une *lampe*.",
         texto=["Une lampe qui grésillait au plafond, que personne d'autre n'entendait. Impossible de suivre la conversation.",
                "Longtemps, j'ai cru que j'exagérais.",
                "Non : mon cerveau classait ce détail minuscule dans la même case qu'une alarme.",
                "Le tien aussi, peut-être. Ce genre d'inconfort mérite qu'on le *retire.*"],
         leyenda="Ton cerveau prend au sérieux ce que les autres n'enregistrent même pas. 💡"),
    # 72
    dict(n=4, hook="Tu mets du temps\nà répondre ?\nC'est de la *profondeur*.",
         texto=["Pendant que d'autres survolent une information, toi tu la fais descendre.",
                "Tu la compares à tout ce que tu as vécu, tu la retournes, tu en explores les recoins.",
                "Là où un esprit prend une photo, le tien fait une plongée. Ça prend plus de temps.",
                "Mais c'est pour ça que tes intuitions tombent si *juste.*"],
         leyenda="Une plongée est toujours plus lente qu'un coup d'œil. 🌊"),
    # 73
    dict(n=67, hook="Tu n'as pas à\nmériter ta place\nen te *vidant*.",
         texto=["Quelque part, tu as appris que ta valeur tenait à ce que tu apportes. Alors tu donnes, tu aides, sans cesse.",
                "Mais ceux qui ne t'aiment que pour ce que tu leur apportes n'aiment pas toi. Ils aiment tes services.",
                "Un enfant qu'on aime n'a rien à apporter pour mériter cet amour. Toi non plus.",
                "Tu mérites l'amour au repos, sans rien produire, juste pour ta *présence.*"],
         leyenda="Ceux qui t'aiment vraiment t'aiment déjà ainsi. 💞"),
    # 74
    dict(n=84, hook="Protéger ton énergie,\nc'est de l'écologie\n*personnelle*.",
         texto=["Refuser une sortie de trop, garder du temps pour toi. Ça te semble égoïste.",
                "Mais ton énergie n'est pas illimitée. Tu dépenses énormément, en continu, pour des choses invisibles.",
                "On ne reproche à personne d'économiser l'eau en période de sécheresse.",
                "Avec des réserves, tu écoutes mieux, tu donnes mieux, tu aimes *mieux.*"],
         leyenda="Prendre soin de tes forces, c'est avoir encore quelque chose à offrir. 🌍"),
    # 75
    dict(n=46, hook="Ton anxiété change\nselon les lieux ?\nCe n'est pas un *hasard*.",
         texto=["Dans certains lieux, avec certaines personnes, elle explose. Ailleurs, elle s'apaise presque d'elle-même.",
                "Un système comme le tien réagit intensément à son environnement, pour le pire comme pour le meilleur.",
                "Avant de te demander « qu'est-ce qui ne va pas chez moi ? », pose-toi une autre question.",
                "Mon environnement est-il fait pour un système comme le *mien* ?"],
         leyenda="Parfois, ce n'est pas toi qu'il faut réparer. C'est ton cadre de vie qu'il faut ajuster. 🏡"),
    # 76
    dict(n=37, hook="Trop chaud, trop fort,\ntrop lumineux ?\nTon détecteur est *fin*.",
         texto=["Tu remarques des inconforts que les autres ne sentent même pas. Et le mot tombe : « chochotte ».",
                "Ton système d'alarme se déclenche simplement à un seuil plus bas.",
                "C'est le même réglage qui te fait remarquer une fausse note, un parfum délicat, une lumière magnifique.",
                "Il sonne plus tôt, pour le pire comme pour le *meilleur.*"],
         leyenda="Personne ne décide à ta place de ce que tu devrais supporter. 🌡️"),
    # 77
    dict(n=8, hook="Ta sensibilité\nn'est pas une\n*maladie*.",
         texto=["Elle ne figure dans aucun manuel de maladies. C'est un trait de tempérament, comme la couleur de tes yeux.",
                "On ne soigne pas un trait. On apprend à vivre avec, à l'aménager, à en tirer le meilleur.",
                "Si c'était une maladie, tu attendrais une guérison qui ne viendrait jamais.",
                "Il n'y a rien à guérir. Il y a seulement quelqu'un à comprendre : *toi.*"],
         leyenda="Une caractéristique, pas une défaillance. 🤍"),
    # 78
    dict(n=97, hook="Les signaux orange\navant la crise :\napprends à les *voir*.",
         texto=["La fatigue qui monte sans raison claire.",
                "L'agacement pour un rien.",
                "La gorge qui se serre, le besoin soudain de fuir une pièce.",
                "Chacun de ces signaux te dit la même chose : c'est le moment de faire une *pause.*"],
         leyenda="Répondre au orange, c'est s'épargner le rouge. 🟠"),
    # 79
    dict(n=75, hook="Une brouille\nte dévaste ?\nTu ressens le *lien*.",
         texto=["Une tension avec quelqu'un que tu aimes, et tu ne penses plus qu'à ça. On te reproche d'en faire trop.",
                "Ce n'est pas que tu as plus besoin des autres. C'est que tu ressens plus fort la fissure du lien.",
                "C'est ta sensibilité, appliquée aux relations.",
                "Et cette même intensité rend tes réconciliations si *profondes.*"],
         leyenda="Tu ne t'accroches pas par faiblesse. Tu ressens la cassure à vif. 🧵"),
    # 80
    dict(n=81, hook="Le but n'est pas\nde t'endurcir.\nC'est de t'*aménager*.",
         texto=["Pendant des années, on t'a vendu une seule solution : t'endurcir.",
                "Mais ta sensibilité ne se muscle pas comme un biceps. C'est ton câblage de fond.",
                "Baisser les lumières trop fortes, ménager des pauses, choisir tes lieux : construire une vie à ta mesure.",
                "Pas une forteresse. Une maison sensible, *confortable.*"],
         leyenda="« Comment aménager un monde qui me convient ? » Cette question-là libère. 🏠"),
    # 81
    dict(n=45, hook="Un terrain fertile\npour l'anxiété n'est\npas une *fatalité*.",
         texto=["Un cerveau qui capte tout et reste activé longtemps offre un terrain où l'anxiété pousse facilement.",
                "Mais un terrain fertile, c'est aussi un terrain qu'on peut cultiver autrement.",
                "Du repos, des limites, du calme : et le même terrain laisse grandir la sérénité.",
                "Ton terrain demande juste plus de *soin.*"],
         leyenda="Prendre soin de son terrain, ça s'apprend. 🌾"),
    # 82
    dict(n=36, hook="Tu aimes savoir\noù tu mets les pieds ?\nC'est de la *stratégie*.",
         texto=["Combien de temps ça durera, s'il y aura du monde, comment tu pourras repartir. On te trouve rigide.",
                "Mais tu sais qu'une sortie te coûte de l'énergie. Alors tu anticipes, pour doser tes forces.",
                "Ce n'est pas de l'angoisse de contrôle. C'est la gestion d'un budget énergétique limité.",
                "Prévoir, pour toi, c'est t'organiser pour *tenir.*"],
         leyenda="Tu gères une ressource rare, et tu le fais avec intelligence. 🗺️"),
    # 83
    dict(n=2, hook="Il n'y a pas eu\nd'erreur à ta\n*fabrication*.",
         texto=["Les autres semblent avoir reçu une notice que tu n'as jamais eue. Ils encaissent, filtrent, laissent glisser.",
                "Mais il n'y a pas eu d'erreur. Il y a eu un réglage.",
                "Comme deux appareils photo : l'un prend une image correcte, l'autre saisit la lumière, le grain, le détail dans l'ombre.",
                "Aucun des deux n'est cassé. Ils ne sont juste pas faits pour la même *chose.*"],
         leyenda="On a appelé ça un défaut. C'était un réglage. 📷"),
    # 84
    dict(n=68, hook="Ce masque\nde « normalité »\nte coûte *cher*.",
         texto=["Sourire quand tu es à plat. Faire comme si le bruit ne te dérangeait pas. Cacher ta fatigue.",
                "Faire semblant en permanence mobilise une énergie énorme, en plus de tout le reste.",
                "Tu paies le prix de ta sensibilité, et aussi celui de la cacher.",
                "Cherche les endroits où tu peux le *tomber.*"],
         leyenda="Là où tu n'as plus à faire semblant, tu cesses de payer double. 🎭"),
    # 85
    dict(n=92, hook="Il y a des gens\nréglés comme toi.\nLes trouver *change tout*.",
         texto=["Tu as peut-être passé ta vie à te sentir en décalage dans le groupe.",
                "Mais une personne sur cinq environ capte tout, ressent fort, a besoin de calme et de profondeur.",
                "Le jour où tu en rencontres une, tu n'as plus rien à expliquer. Elle sait.",
                "Cherche-les dans les lieux calmes et les conversations profondes. Elles te cherchent peut-être *aussi.*"],
         leyenda="Des endroits où tu n'as pas à te traduire. 🤝"),
    # 86
    dict(n=51, hook="Tu imagines\ntoujours le pire ?\nTon radar est *allumé*.",
         texto=["Tu anticipes les problèmes, tu scrutes l'horizon à la recherche de la prochaine menace.",
                "À la base, c'est une qualité : tu sens venir les choses, tu protèges.",
                "Le problème, c'est que ce capteur a pris l'habitude de rester allumé, même quand il n'y a rien à détecter.",
                "Un radar, ça se réapprivoise. Il a le droit de se *reposer.*"],
         leyenda="Pas de la folie : un excellent détecteur qui ne sait plus s'éteindre. 📡"),
    # 87
    dict(n=38, hook="« À cran »\nveut souvent dire\n« à *ras bord* ».",
         texto=["Ces moments où tout t'irrite et où tu ne te reconnais pas.",
                "La plupart du temps, ton système a simplement accumulé : du bruit, des émotions, des sollicitations, jusqu'au dernier centimètre de marge.",
                "« Je suis à cran » invite à serrer les dents. « Je suis à ras bord » invite à vider un peu.",
                "Ce n'est pas le moment de te gronder. C'est le moment de te *délester.*"],
         leyenda="Un contenant arrivé à ras bord, pas une nervosité gratuite. 🫖"),
    # 88
    dict(n=10, hook="Tu te sens à part ?\nUne personne sur cinq\nest réglée comme *toi*.",
         texto=["Entre quinze et trente pour cent des gens sont câblés comme toi.",
                "Dans ta rue, dans ton travail, dans le métro, des dizaines de personnes sont épuisées par le bruit et submergées par les émotions des autres.",
                "Elles ne le disent pas, parce qu'elles ont appris à le cacher.",
                "Tu as cru être une exception. Tu ne l'as jamais *été.*"],
         leyenda="Une minorité nombreuse, silencieuse, présente partout. 👋"),
    # 89
    dict(n=None, hook="Trop fort,\ntrop vite,\ntrop *longtemps* ?",
         texto=["Toute ta vie, ou presque, on t'a fait comprendre que tu ressentais mal.",
                "Que tu prenais tout trop à cœur. Un mot est revenu si souvent que tu as fini par le porter comme une étiquette : trop.",
                "Je connais ce mot par cœur. On me l'a répété pendant des années.",
                "Tu n'es pas trop. Tu ressens *autrement.*"],
         leyenda="Ce n'est pas ta sensibilité qui t'a fait souffrir. C'est de ne l'avoir jamais comprise. 💬"),
    # 90
    dict(n=76, hook="Un message\nsans réponse\nt'*affole* ?",
         texto=["Qu'est-ce que j'ai fait ? Est-ce qu'il m'en veut ? Ton esprit s'emballe pour un silence.",
                "C'est un capteur très ancien, réglé sur une seule chose : la peur de perdre le lien.",
                "Chez toi, il est particulièrement fin, et sonne parfois bien avant qu'il y ait un vrai danger.",
                "Un silence n'est le plus souvent qu'un *silence.*"],
         leyenda="Une alarme trop zélée, qu'on peut apprendre à rassurer. 📱"),
    # 91
    dict(n=95, hook="Tu n'as pas\nà performer la\n« *normalité* ».",
         texto=["Le même rythme, le même nombre de sorties, la même endurance au bruit que les autres. Comme une performance à réussir.",
                "Cette normalité est calibrée pour d'autres systèmes. La viser, c'est courir une course truquée d'avance.",
                "Le problème n'a jamais été ton incapacité à suivre. C'est l'idée que tu devrais.",
                "Tu n'as pas à entrer dans la taille des autres. Tu as à tailler la *tienne.*"],
         leyenda="Pas une version rétrécie de leur vie. Une vie pleine, à ta taille. ✂️"),
    # 92
    dict(n=54, hook="Ton « trop »\net ton anxiété ?\nUne seule *source*.",
         texto=["D'un côté, le sentiment d'être « trop ». De l'autre, l'anxiété qui revient.",
                "Le « trop », c'est ta sensibilité qui reçoit beaucoup. L'anxiété, c'est ce que ça devient quand ce beaucoup dépasse ce que tu peux traiter.",
                "Tu n'as pas deux ennemis à combattre. Tu as une seule dynamique à réguler : le trop-plein.",
                "Agis à la source, et les deux reculent *ensemble.*"],
         leyenda="Deux visages d'une même chose. 🎭"),
    # 93
    dict(n=19, hook="Tu n'as pas des\nsens plus fins. Tu as\nun *filtre* ouvert.",
         texto=["Le cerveau de la plupart des gens trie en permanence : il écarte le bruit de la clim, la conversation d'à côté.",
                "Ton filtre, lui, laisse passer presque tout.",
                "Tu reçois le monde sans tri, en entier, en même temps. C'est épuisant, parce que tout compte pareil.",
                "Mais c'est aussi pour ça que rien ne t'*échappe.*"],
         leyenda="Le détail que les autres ont filtré, toi tu l'as reçu. 🔊"),
    # 94
    dict(n=12, hook="Ni cadeau,\nni fardeau :\nun *réglage*.",
         texto=["Ton système est réglé sur une sensibilité haute. Ce n'est ni bien ni mal : c'est un paramètre, comme le volume d'un appareil.",
                "Et ce qui est réglé peut s'apprivoiser.",
                "Tu peux apprendre à repérer quand ton système monte, et te ménager des pauses avant la saturation plutôt qu'après la crise.",
                "Ce qu'on comprend cesse, peu à peu, de nous faire *peur.*"],
         leyenda="Pas te changer : apprendre ton propre réglage. 🎚️"),
    # 95
    dict(n=59, hook="Épuisement après\navoir écouté quelqu'un ?\nTu as *porté*.",
         texto=["Après une conversation où quelqu'un t'a confié son mal-être, tu ressors parfois avec une partie de son fardeau.",
                "Tu ne comprends pas seulement avec ta tête. Tu ressens son émotion dans ton propre corps.",
                "C'est ce qui fait qu'avec toi, les gens se sentent vraiment accompagnés.",
                "Ce que tu portes pour les autres, tu as le droit de le *reposer.*"],
         leyenda="Cette fatigue n'est pas de la fragilité. C'est le signe que tu as vraiment porté. 🎒"),
    # 96
    dict(n=91, hook="Tes besoins sont\nlégitimes, même\n*incompris*.",
         texto=["Expliquer pourquoi le bruit te dérange, pourquoi tu as besoin de partir. Et quand on ne comprend pas, tu doutes.",
                "Quelqu'un qui n'a jamais vécu ta sensibilité ne peut pas la ressentir de l'intérieur. C'est normal.",
                "Attendre l'accord de tous, c'est confier ta légitimité à des gens qui n'ont pas les moyens de te saisir.",
                "« Je sais que ça te paraît étrange, et j'en ai besoin *quand même.* »"],
         leyenda="Ta légitimité t'appartient, comprise ou non. ✨"),
    # 97
    dict(n=50, hook="L'anxiété n'est pas\nton identité.\nC'est un *signal*.",
         texto=["« Je suis quelqu'un d'anxieux. » Cette phrase enferme.",
                "Ce que tu es par nature, c'est sensible. L'anxiété apparaît quand on force cette nature, quand on t'impose le rythme d'un autre système.",
                "Change le rythme, et tu verras.",
                "Ce que tu prenais pour ta nature n'était qu'une *conséquence.*"],
         leyenda="Pas une identité : le prix d'un rythme qui n'est pas le tien. 🎵"),
    # 98
    dict(n=25, hook="Épuisement après\nune belle soirée ?\nRien n'a été *filtré*.",
         texto=["La soirée était réussie, tu as ri. Et le lendemain, à plat, comme après un marathon sur une chaise.",
                "Pendant que les autres filtraient, ton cerveau recevait tout : le froncement de sourcil en face, la musique, l'humeur de chacun.",
                "Cette fatigue, ce n'est pas toi qui flanches. C'est ton système qui range.",
                "Tu n'aimes pas moins les gens. Tu as juste besoin d'un *lendemain* calme."],
         leyenda="Ton cerveau range enfin tout ce qu'il a capté sans le vouloir. 🛋️"),
    # 99
    dict(n=14, hook="« Endurcis-toi »\nne t'a appris\nqu'une *chose*.",
         texto=["« Arrête de pleurer. » « Sois moins susceptible. » On te l'a dit, souvent avec les meilleures intentions.",
                "Mais on ne rend pas un système sensible moins sensible en le grondant.",
                "Ces phrases t'ont seulement appris à avoir honte de réactions que tu ne choisissais pas.",
                "Cette honte n'a jamais été à toi. Tu peux la *reposer.*"],
         leyenda="L'endurcissement n'a jamais marché. Ta sensibilité est toujours là. 🌱"),
    # 100
    dict(n=None, hook="Ce dont ton système\na vraiment besoin\n(ce n'est pas un *luxe*).",
         texto=["Des plages de silence, chaque jour.",
                "Un lendemain calme après une soirée dense.",
                "Le droit de partir plus tôt, de baisser le son, de dire « c'est trop pour moi ».",
                "Et des gens avec qui tu n'as pas à te *traduire.*"],
         leyenda="Pas des caprices : l'entretien d'un système qui ressent tout. 🧰"),
    # 101
    dict(n=63, hook="Comprendre quelqu'un\nne t'oblige pas\nà *rester*.",
         texto=["Parce que tu comprends les blessures des gens, il te semble devoir rester, pardonner, donner encore une chance.",
                "Mais un incendie a toujours une cause. Ça ne t'oblige pas à rester dans la maison qui brûle.",
                "« Je vois ta douleur, je la comprends, et je pars quand même. »",
                "Ce n'est pas de la dureté. C'est te *protéger.*"],
         leyenda="Ta compréhension ne doit pas devenir la corde qui te retient. 🔥"),
    # 102
    dict(n=97, hook="Une crise\nn'arrive jamais\n« d'un *coup* ».",
         texto=["Avant chaque crise, il y a eu des signaux : la fatigue qui montait, l'agacement, la gorge qui se serrait.",
                "Ton système a clignoté en orange longtemps avant de passer au rouge.",
                "Bonne nouvelle : si la crise a des signes avant-coureurs, tu peux agir avant.",
                "Baisse le flux au voyant orange. Pas au *rouge.*"],
         leyenda="Tu ne peux pas empêcher ton système de se remplir. Tu peux le vider avant qu'il déborde. 🚦"),
    # 103
    dict(n=56, hook="Tu essaies de suivre\nle rythme des autres ?\nArrête de *forcer*.",
         texto=["Des journées pleines, des sorties, du bruit, sans jamais déborder. Tu essaies de tenir la même cadence, et tu t'épuises.",
                "Eux y arrivent parce que leur système est réglé pour ça.",
                "Une mécanique qu'on force finit par surchauffer. Ta surchauffe porte un nom : l'anxiété.",
                "Le jour où tu adoptes ton propre tempo, quelque chose se *relâche.*"],
         leyenda="Tu n'as jamais eu à suivre leur rythme. Tu as à trouver le tien. 🐢"),
    # 104
    dict(n=40, hook="Ça monte\nsouvent le *soir*,\nn'est-ce pas ?",
         texto=["Le cœur qui s'emballe, cette boule, au moment où tu devrais enfin te détendre.",
                "Ce n'est pas qu'un malheur secret t'attend la nuit.",
                "C'est que le silence du soir laisse remonter tout ce que le bruit du jour avait recouvert.",
                "Tes sensations non digérées réclament juste un peu d'espace pour *s'écouler.*"],
         leyenda="Arrête de chercher le drame. Offre-toi un peu d'espace. 🌙"),
    # 105
    dict(n=16, hook="Les conversations\nde surface\nt'*épuisent* ?",
         texto=["Le bavardage pour meubler, les échanges convenus : tu décroches, et tu culpabilises de t'ennuyer.",
                "Ce n'est pas du mépris. Ton cerveau a besoin de sens comme d'autres ont besoin d'air.",
                "C'est pour ça qu'une soirée bruyante peut te sembler plus solitaire qu'une soirée chez toi.",
                "Ce qui compte, ce n'est pas le nombre de gens. C'est la *profondeur* du lien."],
         leyenda="Tu as juste faim d'autre chose : de vrai, de dense, d'essentiel. 🗨️"),
    # 106
    dict(n=69, hook="Tu te sens\n« d'une autre planète » ?\nC'est une *fréquence*.",
         texto=["Les autres s'amusent de choses qui te laissent de marbre, et ignorent ce qui te bouleverse.",
                "Il y a un vrai décalage de perception : tu captes le monde plus profondément, avec plus de nuances.",
                "Ta fréquence est simplement partagée par moins de monde.",
                "Mais peu ne veut pas dire personne. Avec ceux qui la partagent, le décalage *disparaît.*"],
         leyenda="Tu étais juste rarement au bon endroit. 📻"),
    # 107
    dict(n=95, hook="Renoncer\nà ressembler\npour oser *correspondre*.",
         texto=["Vivre comme les autres te demande une énergie folle : même rythme, mêmes sorties, même endurance au bruit.",
                "Construire ta vie à ta taille demande du courage, parce qu'il faut renoncer à ressembler.",
                "Mais de l'autre côté, il y a un soulagement immense.",
                "Celui d'arrêter de forcer, et de vivre enfin dans une vie qui te *va.*"],
         leyenda="Le bon nombre de sorties, le bon calme, les bonnes personnes : les tiens. 🌻"),
    # 108
    dict(n=27, hook="Pleurer sans\nraison précise n'est\npas de l'*instabilité*.",
         texto=["Une fin de journée, un trop-plein, et les larmes montent, sans drame identifiable.",
                "Tu n'as pas besoin d'une raison précise.",
                "Quand ton système a tout encaissé, les larmes remettent l'équilibre, aussi naturellement qu'un soupir après un effort.",
                "Ce sont des larmes qui font le *ménage.*"],
         leyenda="Pleurer, c'est se vider d'un trop-plein qui, sinon, se déposerait ailleurs. 💧"),
    # 109
    dict(n=18, hook="Tu n'as pas\nà te réparer. Juste\nà te *comprendre*.",
         texto=["Peut-être que tu cherchais une méthode pour corriger ce qui, en toi, semblait défaillant.",
                "Mais il n'y a rien de cassé. Il y a un système sensible, profond, longtemps incompris, y compris de toi.",
                "Le but n'est pas de t'en débarrasser. C'est de cesser de te battre contre toi.",
                "Pas te changer. Te *rencontrer.*"],
         leyenda="Ce qui te faisait honte peut devenir ce qui te rend unique. 🪞"),
    # 110
    dict(n=74, hook="Ils ne sont pas\ninsensibles. Ils n'ont\npas *capté*.",
         texto=["Quelque chose te bouleverse, et les gens autour restent de marbre. Tu les crois durs.",
                "Le plus souvent, le signal qui te transperce n'est même pas arrivé jusqu'à eux.",
                "On ne peut pas réagir à ce qu'on ne perçoit pas.",
                "Ce qui est évident pour toi ne l'est pas pour eux. Le *nommer* suffit souvent."],
         leyenda="Ni eux ni toi n'avez tort. Vous ne captez pas les mêmes choses. 📡"),
    # 111
    dict(n=None, hook="On ne corrige pas\nune couleur d'yeux.\nNi une *sensibilité*.",
         texto=["Ce livre n'est pas une méthode pour te corriger.",
                "Ce n'est pas non plus un discours qui te dirait que ta sensibilité est un merveilleux superpouvoir.",
                "C'est un chemin de réconciliation : cent une vérités courtes, que personne ne t'a jamais expliquées.",
                "Pour remettre du sens là où il n'y avait que de la *honte.*"],
         leyenda="Tu peux les lire dans l'ordre, ou en ouvrir une au hasard, le soir. 📖"),
    # 112
    dict(n=78, hook="Trop intense\npour certains ?\nParfait pour les *vrais*.",
         texto=["Tu poses de vraies questions, tu vas vite au fond des choses. Et des gens s'éloignent.",
                "Ceux que ta profondeur fait fuir sont les tièdes, ceux qui préfèrent rester en surface.",
                "Ceux qu'elle retient sont les vrais, ceux qui cherchent comme toi de l'authenticité.",
                "Les bons restent. Et se sentent enfin à la bonne *profondeur.*"],
         leyenda="Ce tri n'est pas une perte. C'est un service que ta nature te rend. 🌊"),
    # 113
    dict(n=100, hook="L'humanité a toujours\neu besoin de\n*veilleurs*.",
         texto=["Dans chaque groupe, certains sentent le danger en premier, remarquent le changement subtil, hésitent avant de foncer.",
                "Ils protègent tout le monde.",
                "Sans les gens qui ressentent fort, le monde irait plus vite, plus fort, plus dur. Et plus aveugle.",
                "Tu es de cette lignée-là. Et elle est *précieuse.*"],
         leyenda="Veilleurs sensibles autant que fonceurs : le monde a besoin des deux. 🔭"),
    # 114
    dict(n=71, hook="À toi qu'on traite\nde susceptible\ndepuis l'*enfance*.",
         texto=["« Arrête de pleurer. » « Sois moins susceptible. » Tu l'as entendu si souvent.",
                "Mais les mots ne glissent pas sur toi. Ils entrent, ils résonnent longtemps.",
                "Ce n'est pas de la susceptibilité. C'est de la porosité, le revers d'une sensibilité qui t'ouvre aussi à la beauté.",
                "La honte qu'on t'a fait porter n'a jamais été à *toi.*"],
         leyenda="Tu peux la reposer maintenant. 🌱"),
    # 115
    dict(n=72, hook="Tu rejoues une\nconversation des heures ?\nTu as tout *capté*.",
         texto=["Les autres tournent la page en un instant. Toi, tu restes dedans.",
                "Pendant l'échange, tu as capté bien plus que les mots : les intonations, les silences, les non-dits.",
                "Il y a simplement plus à traiter.",
                "Ce n'est pas une fixation. C'est une digestion en *profondeur.*"],
         leyenda="Tu as vécu en profondeur un échange que d'autres ont survolé. 🗨️"),
    # 116
    dict(n=79, hook="Sensible\net des limites ?\nC'est ce qui te *sauve*.",
         texto=["Tu crois peut-être que la douceur oblige à tout accepter, à toujours être disponible.",
                "Sans limites, ta sensibilité se retourne contre toi : tu absorbes tout, tu donnes tout, jusqu'à l'épuisement.",
                "Les limites ne te rendent pas moins sensible. Elles protègent ta sensibilité pour qu'elle dure.",
                "Sans berges, il n'y a plus de rivière. Juste une *inondation.*"],
         leyenda="Tes limites sont la condition de ta douceur. 🏞️"),
    # 117
    dict(n=80, hook="Moins de monde,\nplus de vrai : pas\nbesoin de t'*excuser*.",
         texto=["Une soirée à deux plutôt qu'une fête à cinquante. Un ami profond plutôt qu'un grand cercle.",
                "Et souvent, tu t'en excuses, comme d'un défaut de sociabilité.",
                "Tu te nourris de profondeur, pas de quantité. C'est une préférence légitime.",
                "Ce n'est pas t'isoler du monde. C'est choisir le monde qui te *convient.*"],
         leyenda="On vit dans un monde qui valorise le beaucoup. Toi, tu choisis le vrai. 🕯️"),
    # 118
    dict(n=59, hook="Les gens\nse confient à toi ?\nCe n'est pas un *hasard*.",
         texto=["Tu perçois sans qu'on t'explique : les postures, les silences, ce qui n'est pas dit.",
                "Quand quelqu'un te parle, tu ne comprends pas seulement avec ta tête. Tu ressens avec lui.",
                "C'est pour ça qu'avec toi, les gens se sentent vraiment accompagnés.",
                "Et ce que tu portes pour eux, tu as le droit, ensuite, de le *déposer.*"],
         leyenda="Écouter vraiment est rare. Te reposer après l'est tout autant. 🫖"),
    # 119
    dict(n=None, hook="Ce que ta sensibilité\nessaie de te dire,\nen 5 *étapes*.",
         texto=["Un : comprendre ton réglage. Rien n'a jamais été cassé.",
                "Deux : décoder ce corps qui capte tout. Trois : découvrir que beaucoup de ce que tu prends pour de l'angoisse est ta sensibilité qui déborde.",
                "Quatre : aimer les autres sans te laisser envahir. Cinq : aménager ta vie à ta mesure, et récolter ce que ta sensibilité offre de plus *beau.*"],
         leyenda="Le chemin du livre, en cinq étapes. Tu en es où ? 🗺️"),
    # 120
    dict(n=None, hook="Ta sensibilité s'apaise\nquand tu lui donnes\nun *espace*.",
         texto=["Comprendre, c'est déjà beaucoup.",
                "Mais ta sensibilité ne s'apaise pas seulement dans la tête.",
                "Elle s'apaise quand tu sors de tes pensées pour poser, quelque part, ce que tu portes.",
                "Un carnet, un moment, un endroit où déposer ton *trop-plein.*"],
         leyenda="Reviens à ta vérité préférée les jours où le monde te semble trop grand. 📓"),
]
